FROM nginx:1.25-alpine

# nginx 설정 파일 복사
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# 로그 디렉터리 권한 설정
RUN mkdir -p /var/log/nginx && \
    chmod -R 755 /var/log/nginx

# nginx 포트 노출
EXPOSE 80

# nginx 실행
CMD ["nginx", "-g", "daemon off;"]
