server {
	listen 80;
	server_name net_admin.local;

	# FastAPI static files (swagger-ui)
	location /static/swagger-ui/ {
		proxy_pass http://fastapi:8000/static/swagger-ui/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	# Django: static files
	location /static/ {
		alias /app/staticfiles/;
		autoindex on;
	}

	# FastAPI
	location /api/ {
		proxy_pass http://fastapi:8000/api/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	# Django: main application
	location / {
		proxy_pass http://django:8080;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
